### PR TITLE
Add running average and running standard deviation

### LINKED ISSUE #5: Suggestion: Add 'rolling average' option to more accurately display server health
Over long login sessions the average server health value gets skewed if the server suddenly degrades in performance (or improves). If the plugin could be configured to use data points from the last 5 minutes for example, it may provide a more accurate representation of the servers actual health. 

Thanks very much for all your work on the plugin!

### PR DESCRIPTION
**Pull request by Toocanzs**
Fixes #5 

The running average isn't quite as useful as you would think as It just converges on 600ms, but the standard deviation is a good measure of how much the ticks are varying. Higher = worse.

image

### CODE REVIEW

**Comment by Tatters654** [comment]
This is only for statistical uses, or did you have further plans on using statistic this in some way?

**Comment by Toocanzs** [comment]
Yea I just use the standard deviation as a quick number to glance at to see how good the server is. 

I don't really have any other plans to use the statistics, although you could use the standard deviation to calculate the things like what percentage of deltas are greater than X or similar, but this is already calculated exactly by your existing code so it seems a bit silly.

**Comment by Tatters654** [comment]
Sure, this seems like a good change. Perhaps add something to the readme about it?

**Comment by Toocanzs** [comment]
Updated the readme

**Comment by Tatters654** [comment]
Hi. Do you still play OSRS? If so, can you verify whether this plugin works currently with the master branch? I don't think the plugin hub manifest was ever updated, leading to newer changes never being distributed. I don't actively play anymore, but if you or @Infinitay could confirm that the build & plugin works, I can update the manifest.

**Comment by Infinitay** [comment]
> Hi. Do you still play OSRS? If so, can you verify whether this plugin works currently with the master branch? I don't think the plugin hub manifest was ever updated, leading to newer changes never being distributed. I don't actively play anymore, but if you or @Infinitay could confirm that the build & plugin works, I can update the manifest.


I'm on version 1.1 and AFAIK it's working fine, not that I'm in expert in things tick related. However, based on my plugin settings, I can feel the game lagging anytime it's below 90%.

EDIT: I'm not sure if you need to update the plugin version itself. The git hash that's on the [plugin hub](https://github.com/runelite/plugin-hub/blob/master/plugins/ticktracker) currently is `a1c5d170529f54e78d52f67874458c27329f88a6` and that was the recent commit https://github.com/Tatters654/tick-tracker/commit/a1c5d170529f54e78d52f67874458c27329f88a6 prior to the plugin tag changes you merged from me (#11). So AFAIK the "newer changes" were being distributed. Feel free to double check with RL Discord.

**Pull request merged**
